# This file was generated by GoReleaser. DO NOT EDIT.
cask "goreload" do
  name "goreload"
  desc "Hot reload tool for Go applications"
  homepage "https://github.com/taro33333/goreload"
  version "0.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "goreload"

  on_macos do
    on_intel do
      url "https://github.com/taro33333/goreload/releases/download/v#{version}/goreload_#{version}_Darwin_x86_64.tar.gz"
      sha256 "d049a4f61d44ea48e196c2b1236d49852d0c318150ebc9d0c7ff3777a8cd958a"
    end
    on_arm do
      url "https://github.com/taro33333/goreload/releases/download/v#{version}/goreload_#{version}_Darwin_arm64.tar.gz"
      sha256 "f2a84f6656418ef91cb97eb1f3b35c1bcd08fb8497ed21a11ed1437dde3e63c3"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/taro33333/goreload/releases/download/v#{version}/goreload_#{version}_Linux_x86_64.tar.gz"
      sha256 "72954419428454ff37b73b32b0542ddedb1e210600de067533bae5d83162a474"
    end
    on_arm do
      url "https://github.com/taro33333/goreload/releases/download/v#{version}/goreload_#{version}_Linux_arm64.tar.gz"
      sha256 "27e0445c2e2503cb30ed483b091623ea407cc2f13ef05d9db1ae970d4047cd53"
    end
  end

  # No zap stanza required
end
